### ISSUE TITLE
Redundant repo?

### ISSUE THREAD

**Issue by basememara** [batoulapps/adhan-swift#4]
Salaam, I'm trying to understand the purpose or goal of this repo. I see `batoulapps/Adhan` is still being maintained, but is this a repo for a future version? I was also confused since there are other languages in the `Shared` folder. JAK

**Comment by z3bi** [comment]
`batoulapps/Adhan` is being kept for two reasons. One is to add it as a subtree to the different language specific repos in order to access the test data in the `Times/` directory so we can verify that all the different language specific implementations have the same results. The second reason is be a central place to open issues such as adding new methods or test data, issues that would apply to all the different implementations.

**Comment by basememara** [comment]
I see, got it. I'm wondering is the `Shared` subtree necessary, or maybe the `Times` directory should be separated out into yet another repo and that's the subtree that gets added to each language-specific repo. The other languages mixed into the repo is a little misleading I think.

**Comment by basememara** [comment]
..if separated out, maybe it would encourage other prayer libraries to use it and extend it with their own tests.

**Comment by sgtsquiggs** [comment]
perhaps `adhan-testdata`. I agree the old repo was/is confusing and keeping it around as-is doesn't help. Downside of removing it is breaking any existing references from developers.

**Comment by z3bi** [comment]
Well my goal was to remove other languages from the main `Adhan` repo (they would still be there in old commits/tags) and it would basically just become the "testdata" repo.

**Comment by basememara** [comment]
Cool sounds good, it can even store scientific and/or fiqh documents, generic API documentation, and global discussions. I see now.. Thx
