### ISSUE TITLE
Which highlatituderule to use?

### ISSUE THREAD

**Issue by zeitoun26** [batoulapps/adhan-swift#46]
So I'm a bit confused.

```
Fajr is at the end of the first seventh of the night and isha is at the beginning of the last seventh of the night. This is recommended to use for locations above 55° latitude to prevent prayer times that would be difficult to perform.
```

This states above 55 degrees, in an question someone asked it was stated above 50 degrees you should use seventhOfTheNight, and the new recommended func has > 48. 

So I'm not sure which is best to use? Also, I couldn't use the recommended func because it's not set to public I believe.

**Comment by ameirwillowtree** [comment]
This is a good point, the 55 degrees is where ALL calculation methods will have unfeasible fajr and isha times during summer. At 48 degrees some calculation methods would start to see difficult times in the summer.

Because now the code will only use the high latitude approximation if its the more favorable time, its recommended to always have it in place starting at 48 degrees. I will go ahead and update the README.

I also believe we need to publish the latest changes to Cocoapods and create a git tag for SPM to use.

**Comment by zeitoun26** [comment]
Ok and there won't be any issues with timings going way off at 48 degrees rather than 55 for example in some calculation methods?

**Comment by ameirwillowtree** [comment]
The times won't be "wrong", it's just enforcing a max/min to keep things from being too difficult which is the generally suggested fiqh ruling. The harder question to answer is if these are the times that the user is expecting, for example do they match the times at their local masjid. Thats a much harder question to answer.

**Comment by zeitoun26** [comment]
I see that makes sense. Ok yeah that's the issue I'm facing. Thank you so much
