### ISSUE TITLE
Issue with nextPrayer

### ISSUE THREAD

**Issue by ahamedsaifudeen** [batoulapps/adhan-swift#7]
nextPrayer prayer is really handy. I see an issue with the nextPrayer after Isha. nextPrayer returns nil after Isha, technically it should return Fajr (for next day) as the next prayer. Can you please look into it?

**Comment by z3bi** [comment]
This is intentional. If we returned fajr then there would be no difference between today's fajr and tomorrow's fajr so we would have to create a new enum case for tomorrowFajr but this would not be a valid parameter in the `time(for prayer)` function. I think returning nil is a reasonable expectation that the developer can look for and then display tomorrow's fajr to the user.

**Comment by z3bi** [comment]
@ahamedsaifudeen there is a Sunnah Times struct you can get that has the middle of the night and last third of the night dates https://github.com/batoulapps/adhan-swift#sunnah-times

You could use that information to then decide what status to show users.
